### ISSUE TITLE
CSRF attack, state parameters do not match.

### ISSUE THREAD

**Issue by debasha** [ArkeologeN/node-linkedin#38]
Hi,
I am using node-linkedin in my application. Till yesterday it was working fine. Today it gave us the problem of "CSRF attack, state parameters do not match.".

As provided in the documentation I am using state parameter :+1: 
 Linkedin.auth.getAccessToken(res, req.query.code, req.query.state, function(err, results) {
if ( err )
            return console.error(err);
-------

Kindly help me on this

**Comment by gotha229a0** [comment]
Hello,

I'm experimenting the same error on same cases.

This is probably caused because user take too long writing his password and code became expired?

Thanks!

**Comment by gotha229a0** [comment]
Hello again,

@debasha 

The problem isn't with node-linkedin.

The problema is with your linkedin settings application, you must complete all the required fields in your application , then go to settings and uncheck all permissions, update settings and now check permissions that you need, "r_fullprofile" doesn't exist now, and this is because your app probably returning this error.

King Regards

**Comment by debasha** [comment]
Thanks a lot,
Yes , this is because of extra scope added . I have used only the scopes that is defined in my linkedin developer application and it is working perfectly fine. Thanks for the help.


Regards,
Deba Sharma,
Lead - Software
Digital Media and Technology at Synechron
Mobile: +91. 9028 0908 57
SYNECHRON -
- 4,000+ professionals globally.
- USA | Canada | UK | The Netherlands | UAE | India | Singapore | Hong Kong | Japan
[cid:image001.jpg@01D08E63.9779E900]<http://www.synestudio.com/>
A Digital Division of Synechron

**Comment by ArkeologeN** [comment]
I presume - the issue has been fixed @debasha :) Closing it now.
